spring:
  # JWT
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    access-duration: 1800000
    refresh-duration: 604800000

  #Database Access Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin

  #H2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  #JPA
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
    database-platform: org.hibernate.dialect.H2Dialect